language: java
jdk:
- openjdk11
deploy:
  provider: heroku
  api_key:
    secure: hGYK/SBW7tRAMtiMAlcZKteuswPqQcfbmlqCOrtjAUhrZj6yYtwzLJdKVXLh73wS8EePhAeqLG3hqDqslIEaKPYLh+ih0pKqVqtvSdZfOzbDvY2YoXGbPhwinZ8bG8o/K1RgQRVbAksK8MctVQ6qV9jDUsjDlTHj502GwH7BooQGcK40hnA0yS17K+qx7OsuEECNcneOeV9I4xxd6eBbM6LtCA2caInllLN06WoMrLlBc+ZN4UlYociIgwqgu9q3DZJ5kifwh05+z4BIVkwwhwh4ATfrKl5pgsG92X7i8Xw8lh+V6mKalJPhm7XZDLrxjYCu3sJLrrmZefHWmPjmqkvdaSx1dNByaifcIZ8MesQg2il3J6EsW7+Sp7dRXLRRljlq0bwWMT6YSxtX2XWWGUPaliwAbfP41zEXbXC2tQ1XNeey7TAjSiDe7bo+R/EEvqAGYBLLay2DotmeaPlcFUhs6wDOMbqzmcdaMxth++VmCiwG+M6leg4dKsI1cUEGvY3h1pCOdp6+NPit36v1Oajj86vKEsfaoqCoY6BVfrS5IMLhNbIfL6+SSoeATtyicTUlQyj+jkAotmNsy1gSmL4XB+nBKg3gpHsmGO9tkogctNlcyB+qmBiD8fjSUWKS4tH6lErC67F28VRhDKCKDjWGt+dajG+NqfIajEGOBZs=
