spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#      url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
#      driverClassName: org.h2.Driver

auth:
  username: ${APP_USERNAME:admin}
  password: ${APP_PASSWORD:password}